FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh \
&& bash nodesource_setup.sh \
&& apt install nodejs \
&& echo NodeJs ver. $(node -v) \
&& echo Npm ver. $(npm -v)

WORKDIR /app